### ISSUE TITLE
Docker "registry mirror" (pull through cache) cannot be setup

### ISSUE THREAD

**Issue by fzyzcjy** [kubernetes-sigs/kind#1775]
**What happened**:
I want to set up [docker registry as a pull cache](https://docs.docker.com/registry/recipes/mirror/) but failed. I have tried [the doc](https://kind.sigs.k8s.io/docs/user/local-registry/) but still fail. The doc talks about "local registry", but my goal is to make my local registry be *a mirror* of the original docker hub. In other words, e.g, when I run `busybox:latest` image, it will ask my local registry for the image data, instead of fetching hub.docker.com.

My attempts and things that may be helpful:

1. It works very well with Minikube. I just use `minikube start --cpus=6 --memory=16000MB --driver=docker --disk-size='100g' --registry-mirror="http://host.docker.internal:5000" --insecure-registry="host.docker.internal:5000"` to start minikube and then everything goes pretty well.
2. When run `curl http://host.docker.internal:5000/v2/` inside the `kind` (go inside by `docker exec -it $(docker ps -aqf "name=kind-control-plane") /bin/bash`), it outputs `{}` and my registry prints out a log `172.17.0.1 - - [08/Aug/2020:10:58:31 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.65.3"`. Thus, it seems that the url `http://host.docker.internal:5000` can be accessed inside Kind.

Thanks!

**What you expected to happen**:
N/A

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a local "pull through cache" registry. I use the following `docker-compose.yaml` with `docker-compose up`

```
registry:
  image: registry:2
  ports:
    - 0.0.0.0:5000:5000
  environment:
    REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
  volumes:
    - /Users/tom/opt/my-docker-registry:/var/lib/registry # change to whatever you want or remove it
```

2. start kind by `kind create cluster --config=./k8s-kind-config.yaml` with config:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users
        containerPath: /Users
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5000"]
    endpoint = ["http://host.docker.internal:5000"]
```

3. try to start a simplest pod, e.g.

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - #
#      image: busybox # can try this, also fail
      image: host.docker.internal:5000/library/busybox:latest
      command:
        - sleep
        - "3600000"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Never
```

However, it does not work :( Our docker registry does *not* receive any http request.

**Anything else we need to know?**:
N/A

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`): 1.18.6 client version
- Docker version: (use `docker info`): 19.03.8
- OS (e.g. from `/etc/os-release`): macos

**Comment by BenTheElder** [comment]
the docs are written for 0.8.x, not 0.7.0. sorry

**Comment by BenTheElder** [comment]
bug => support, 0.7.X is not getting any further releases.

You're going to need to add your registry to NO_PROXY / no_proxy (whichever you use)

**Comment by fzyzcjy** [comment]
Thanks! However it seems that I already add noproxy - 

```
export http_proxy="http://192.168.0.103:10080"; export https_proxy="http://192.168.0.103:10080"; export no_proxy="localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,172.17.0.0/24,192.168.64.0/24,172.17.0.0/16,192.168.65.0/24,192.168.0.103,host.docker.internal"; export HTTP_PROXY=$http_proxy; export HTTPS_PROXY=$https_proxy; export NO_PROXY=$no_proxy;
```

But it still does not work :(

**Comment by BenTheElder** [comment]
0.7.X isn't under active development / testing, I don't think you can just use host.docker.internal on mac?

**Comment by BenTheElder** [comment]
if you can figure out no_proxy either manually with 0.8.X, or by using kind from HEAD (the latest sources), then you can just put the registry onto the `kind` network and refer to the registry by hostname, as in https://kind.sigs.k8s.io/docs/user/local-registry/

**Comment by fzyzcjy** [comment]
Thanks! I will try that

**Comment by BenTheElder** [comment]
v0.9.0 will be out very soon, the proxy issues should be resolved then.

**Comment by Den5i** [comment]
It's still an issue for me even in the v0.10.0 - image v1.17.17 - pulling from the registry mirror results in 'not found' error. 
Cluster configs contain:
```
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:${reg_port}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.somecompany.com"]
    endpoint = ["docker.somecompany.com"]
``` 
error from pod description:
```
Failed to pull image "docker.somecompany.com/busybox:1.29.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.somecompany.com/busybox:1.29.2": failed to resolve reference "docker.somecompany.com/busybox:1.29.2": docker.somecompany.tech/busybox:1.29.2: not found
```

I am using Nexus docker hub proxy repository. 

@fzyzcjy @BenTheElder was it resolved for you?

**Comment by BenTheElder** [comment]
> [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
>    endpoint = ["http://${reg_name}:${reg_port}"]

This part is not a valid config on it's own, unless something is substituting `${reg_port}` etc. before it is passed to kind. there's no environment variable expansion in kind or containerd for this.


> [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.somecompany.com"]
>    endpoint = ["docker.somecompany.com"]

That config does nothing useful, it just says "fetch docker.somecompany.com images from docker.somecompany.com" which is already what would happen with no config.

If you intend to use an HTTP(s) proxy to implement registry mirroring you need to set the environment variables HTTPY_PROXY, HTTPS_PROXY, NO_PROXY, and you may need to copy in the certs.

If you intend `docker.somecompany.com` to be a mirror for docker.io, you want docker.io to be the thing being mirror on the `[plugins.` line

https://github.com/containerd/containerd/blob/master/docs/cri/registry.md

**Comment by Den5i** [comment]
@BenTheElder thanks, although my intentions are that in my pod specs I have 
```
      initContainers:
        - name: do-something
          image: "docker.somecompany.com/busybox:1.29.2"
  ```
  Where `docker.somecompany.com` is a group type Nexus repository which acts as a hosted repository if an image is present locally or as a proxy for `https://registry-1.docker.io` if image is not stored locally. It works just fine with the `docker pull` but doesn't with `crictl pull` unfortunately.

**Comment by BenTheElder** [comment]
> Where docker.somecompany.com is a group type Nexus repository which acts as a hosted repository if an image is present locally or as a proxy for https://registry-1.docker.io

you want something like:
```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["docker.somecompany.com", "https://registry-1.docker.io"]
```

>  It works just fine with the docker pull but doesn't with crictl pull unfortunately.

That's because you have this configured against your host docker, but not against the containerd in the nodes. They're different runtime instances with different config.

**Comment by Den5i** [comment]
Yes, this might work, although then I probably should remove the `docker.somecompany.com/` from the pod specs. 👍
