### ISSUE TITLE
Install fails due to dependency certificate issue

### ISSUE THREAD

**Issue by eero-t** [kubernetes-sigs/kind#3970]
**How to reproduce it (as _minimally_ and precisely as possible)**:

Try installing:
```
$ go install sigs.k8s.io/kind@v0.29.0
```

**What happened**:

Dependency certificate is not accepted:
```
$ go install sigs.k8s.io/kind@v0.29.0
go: downloading sigs.k8s.io/kind v0.29.0
go: downloading al.essio.dev/pkg/shellescape v1.5.1
go/pkg/mod/sigs.k8s.io/kind@v0.29.0/pkg/exec/helpers.go:26:2: unrecognized import path "al.essio.dev/pkg/shellescape": https fetch: Get "https://al.essio.dev/pkg/shellescape?go-get=1": tls: failed to verify certificate: x509: certificate signed by unknown authority
$ go version
go version go1.24.4 linux/amd64
```

**What you expected to happen**:

Install to succeed.

**Environment:**

Fedora 42.

**Anything else we need to know?**:

* Filed bug also to dependency project: https://github.com/alessio/shellescape/issues/59
* Last version that can be installed is v0.26:
```
$ go install sigs.k8s.io/kind@v0.26.0
go: downloading sigs.k8s.io/kind v0.26.0
go: downloading github.com/alessio/shellescape v1.4.2
go: downloading github.com/google/safetext v0.0.0-20220905092116-b49f7bc46da2
```

**Comment by eero-t** [comment]
Appears to have been changed to a less well maintained site from GitHub in https://github.com/kubernetes-sigs/kind/pull/3841.

**Comment by stmcginnis** [comment]
Thanks for the report, but I believe we will need to wait for the dependency project to fix. We can track it here to make sure it's visible to `kind` users.

**Comment by BenTheElder** [comment]
> Appears to have been changed to a less well maintained site from GitHub in https://github.com/kubernetes-sigs/kind/pull/3841.

Yeah, due to https://github.com/kubernetes-sigs/kind/issues/3840.

I see you filed https://github.com/alessio/shellescape/issues/59, thanks.

We should consider re-introducing `vendor/`.

Downsides:
- bloats git repo
- requires running an extra script or command when updating dependencies

Upsides:
- insulated from changes like this
- insulated from dependencies being deleted
- much easier to review dependency changes for safety (you can literally inspect the diff)

cc @aojea

**Comment by BenTheElder** [comment]
As a fallback you can install from a binary in the meantime.

**Comment by BenTheElder** [comment]
I think al.essio.dev/pkg/shellescape was fixed?

**Comment by eero-t** [comment]
Weird. On another Fedora 42 machine the install worked (at least last evening), but on the original one it still fails to same error:
`failed to verify certificate: x509: certificate signed by unknown authority`

No idea whether it's  related, but the machine where things (still) fail, is upgraded across many Fedora versions and uses network through corporate proxy, and one where install succeeded, is from-scratch install accessing (in this case) network directly.  They have some differences also in package versions and what's installed on them, but I don't think that should be something affecting what certs are accepted...

Does the install work for the others currently?

**Comment by stmcginnis** [comment]
Seems to work for me.

![Image](https://github.com/user-attachments/assets/f4472540-fa75-4550-9bd2-0e5bfb5ec313)

You mention a corporate proxy. That makes me a little suspicious. Might be good to check in with whoever runs that to see if there's something it could be doing that would trigger this issue.

**Comment by BenTheElder** [comment]
Not only is the install working, but if I just browse to https://al.essio.dev/pkg/shellescape chrome reports that the certs are fine. As does `curl -vL https://al.essio.dev/pkg/shellescape`.

**Comment by eero-t** [comment]
> Not only is the install working, but if I just browse to https://al.essio.dev/pkg/shellescape chrome reports that the certs are fine.

Hm. Both the `go get` and curl work now.   No idea whether things changed at my (company) or `al.essio.dev` end.

(Strangely the curl output includes several times the line `server: GitHub.com`.)

I get following from Firefox, and something similar from Chromium though:
> Did` Not Connect: Potential Security Issue
> ...
> al.essio.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.
> 
> The issue is most likely with the website, and there is nothing you can do to resolve it.
>
> If you are on a corporate network or using antivirus software, you can reach out to the support teams for assistance. You can also notify the website’s administrator about the problem.

But closing this as `go get` works now.
